/* tslint:disable */
/* eslint-disable */
/**
 * NIMA AI Server
 * API for interacting with NIMA AI agents
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface HTTPValidationError
 */
export interface HTTPValidationError {
    /**
     * 
     * @type {any}
     * @memberof HTTPValidationError
     */
    'detail'?: any;
}
/**
 * 
 * @export
 * @interface ScreenerPayload
 */
export interface ScreenerPayload {
    /**
     * 
     * @type {any}
     * @memberof ScreenerPayload
     */
    'query': any;
    /**
     * 
     * @type {any}
     * @memberof ScreenerPayload
     */
    'holdings'?: any;
    /**
     * 
     * @type {any}
     * @memberof ScreenerPayload
     */
    'positions'?: any;
    /**
     * 
     * @type {any}
     * @memberof ScreenerPayload
     */
    'orders'?: any;
    /**
     * 
     * @type {any}
     * @memberof ScreenerPayload
     */
    'conversation_id'?: any;
}
/**
 * 
 * @export
 * @interface ValidationError
 */
export interface ValidationError {
    /**
     * 
     * @type {any}
     * @memberof ValidationError
     */
    'loc': any;
    /**
     * 
     * @type {any}
     * @memberof ValidationError
     */
    'msg': any;
    /**
     * 
     * @type {any}
     * @memberof ValidationError
     */
    'type': any;
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Fno Scheduler Caller
         * @param {any} agentType 
         * @param {any} identifier 
         * @param {any} [expiryOrPage] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fnoSchedulerCallerRouteRunManualSchedulerPost: async (agentType: any, identifier: any, expiryOrPage?: any, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'agentType' is not null or undefined
            assertParamExists('fnoSchedulerCallerRouteRunManualSchedulerPost', 'agentType', agentType)
            // verify required parameter 'identifier' is not null or undefined
            assertParamExists('fnoSchedulerCallerRouteRunManualSchedulerPost', 'identifier', identifier)
            const localVarPath = `/route/run_manual_scheduler`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (agentType !== undefined) {
                localVarQueryParameter['agent_type'] = agentType;
            }

            if (identifier !== undefined) {
                localVarQueryParameter['identifier'] = identifier;
            }

            if (expiryOrPage !== undefined) {
                localVarQueryParameter['expiry_or_page'] = expiryOrPage;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Health Check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthCheckHealthGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/health`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List Vector Files
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listVectorFilesVectorFilesGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/vector_files`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Root
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        rootGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Route Stream
         * @param {{ [key: string]: any; }} requestBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        routeStreamRouteStreamPost: async (requestBody: { [key: string]: any; }, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'requestBody' is not null or undefined
            assertParamExists('routeStreamRouteStreamPost', 'requestBody', requestBody)
            const localVarPath = `/route/stream`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(requestBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Natural language stock screener Example queries: - PE < 10 - PE vs PB - Best stocks to buy
         * @summary Screener
         * @param {ScreenerPayload} screenerPayload 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        screenerScreenerPost: async (screenerPayload: ScreenerPayload, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'screenerPayload' is not null or undefined
            assertParamExists('screenerScreenerPost', 'screenerPayload', screenerPayload)
            const localVarPath = `/screener`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(screenerPayload, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Fno Scheduler Caller
         * @param {any} agentType 
         * @param {any} identifier 
         * @param {any} [expiryOrPage] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async fnoSchedulerCallerRouteRunManualSchedulerPost(agentType: any, identifier: any, expiryOrPage?: any, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.fnoSchedulerCallerRouteRunManualSchedulerPost(agentType, identifier, expiryOrPage, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Health Check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async healthCheckHealthGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.healthCheckHealthGet(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary List Vector Files
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listVectorFilesVectorFilesGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listVectorFilesVectorFilesGet(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Root
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async rootGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.rootGet(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Route Stream
         * @param {{ [key: string]: any; }} requestBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async routeStreamRouteStreamPost(requestBody: { [key: string]: any; }, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.routeStreamRouteStreamPost(requestBody, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Natural language stock screener Example queries: - PE < 10 - PE vs PB - Best stocks to buy
         * @summary Screener
         * @param {ScreenerPayload} screenerPayload 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async screenerScreenerPost(screenerPayload: ScreenerPayload, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.screenerScreenerPost(screenerPayload, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary Fno Scheduler Caller
         * @param {any} agentType 
         * @param {any} identifier 
         * @param {any} [expiryOrPage] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fnoSchedulerCallerRouteRunManualSchedulerPost(agentType: any, identifier: any, expiryOrPage?: any, options?: any): AxiosPromise<any> {
            return localVarFp.fnoSchedulerCallerRouteRunManualSchedulerPost(agentType, identifier, expiryOrPage, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Health Check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthCheckHealthGet(options?: any): AxiosPromise<any> {
            return localVarFp.healthCheckHealthGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List Vector Files
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listVectorFilesVectorFilesGet(options?: any): AxiosPromise<any> {
            return localVarFp.listVectorFilesVectorFilesGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Root
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        rootGet(options?: any): AxiosPromise<any> {
            return localVarFp.rootGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Route Stream
         * @param {{ [key: string]: any; }} requestBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        routeStreamRouteStreamPost(requestBody: { [key: string]: any; }, options?: any): AxiosPromise<any> {
            return localVarFp.routeStreamRouteStreamPost(requestBody, options).then((request) => request(axios, basePath));
        },
        /**
         * Natural language stock screener Example queries: - PE < 10 - PE vs PB - Best stocks to buy
         * @summary Screener
         * @param {ScreenerPayload} screenerPayload 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        screenerScreenerPost(screenerPayload: ScreenerPayload, options?: any): AxiosPromise<any> {
            return localVarFp.screenerScreenerPost(screenerPayload, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary Fno Scheduler Caller
     * @param {any} agentType 
     * @param {any} identifier 
     * @param {any} [expiryOrPage] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public fnoSchedulerCallerRouteRunManualSchedulerPost(agentType: any, identifier: any, expiryOrPage?: any, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).fnoSchedulerCallerRouteRunManualSchedulerPost(agentType, identifier, expiryOrPage, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Health Check
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public healthCheckHealthGet(options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).healthCheckHealthGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List Vector Files
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public listVectorFilesVectorFilesGet(options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).listVectorFilesVectorFilesGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Root
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public rootGet(options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).rootGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Route Stream
     * @param {{ [key: string]: any; }} requestBody 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public routeStreamRouteStreamPost(requestBody: { [key: string]: any; }, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).routeStreamRouteStreamPost(requestBody, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Natural language stock screener Example queries: - PE < 10 - PE vs PB - Best stocks to buy
     * @summary Screener
     * @param {ScreenerPayload} screenerPayload 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public screenerScreenerPost(screenerPayload: ScreenerPayload, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).screenerScreenerPost(screenerPayload, options).then((request) => request(this.axios, this.basePath));
    }
}


