export const sampleOrders = [
  {
    product: "MIS",
    variety: null,
    identifier: "NSE:SBICARD",
    symbol: "SBICARD-EQ",
    order_type: "LIMIT",
    quantity: 1,
    lots: 1,
    price: 0,
    average_price: 0,
    token: "101000000017971",
    exchange: "NSE",
    option_type: null,
    lot_size: 1,
    expiry_date: "",
    order_id: "26010700354689",
    order_id_unique: "",
    status: "OPEN",
    transaction_type: "SELL",
    update_time: "07-Jan-2026 15:05:17",
    description: "",
    display_symbol_name: "SBICARD-EQ",
  },
  {
    product: "MIS",
    variety: null,
    identifier: "NSE:NIFTYQLITY",
    symbol: "NIFTYQLITY-EQ",
    order_type: "MARKET",
    quantity: 1,
    lots: 1,
    price: 0,
    average_price: 0,
    token: "101000000010690",
    exchange: "NSE",
    option_type: null,
    lot_size: 1,
    expiry_date: "",
    order_id: "26010700354942",
    order_id_unique: "",
    status: "COMPLETED",
    transaction_type: "BUY",
    update_time: "07-Jan-2026 15:05:33",
    description: "",
    display_symbol_name: "NIFTYQLITY-EQ",
  },
  {
    product: "MIS",
    variety: null,
    identifier: "NSE:NIFTYQLITY",
    symbol: "NIFTYQLITY-EQ",
    order_type: "MARKET",
    quantity: 1,
    lots: 1,
    price: 0,
    average_price: 0,
    token: "101000000010690",
    exchange: "NSE",
    option_type: null,
    lot_size: 1,
    expiry_date: "",
    order_id: "26010700355241",
    order_id_unique: "",
    status: "COMPLETED",
    transaction_type: "SELL",
    update_time: "07-Jan-2026 15:05:56",
    description: "",
    display_symbol_name: "NIFTYQLITY-EQ",
  },
  {
    product: "MIS",
    variety: null,
    identifier: "NSE:IOB",
    symbol: "IOB-EQ",
    order_type: "MARKET",
    quantity: 1,
    lots: 1,
    price: 36.68,
    average_price: 36.68,
    token: "10100000009348",
    exchange: "NSE",
    option_type: null,
    lot_size: 1,
    expiry_date: "",
    order_id: "26010700358495",
    order_id_unique: "1100000075056921",
    status: "COMPLETED",
    transaction_type: "BUY",
    update_time: "07-Jan-2026 15:09:23",
    description: "",
    display_symbol_name: "IOB-EQ",
  },
  {
    product: "MIS",
    variety: null,
    identifier: "NSE:JIOFIN",
    symbol: "JIOFIN-EQ",
    order_type: "MARKET",
    quantity: 1,
    lots: 1,
    price: 0,
    average_price: 0,
    token: "101000000018143",
    exchange: "NSE",
    option_type: null,
    lot_size: 1,
    expiry_date: "",
    order_id: "26020600390896",
    order_id_unique: "",
    status: "REJECTED",
    transaction_type: "BUY",
    update_time: "06-Feb-2026 16:44:43",
    description: "RED:'MIS' Orders are disallowed after system square off",
    display_symbol_name: "JIOFIN-EQ",
  },
];
